name: CI/CD for Netlify Deployment

on:
  push:
    branches:
      - master
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.2.0"
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: |
          export NODE_OPTIONS=--experimental-vm-modules
          npm run build

      - name: Link to Netlify Site
        run: netlify link --id ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Deploy to Netlify
        run: netlify deploy --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir=dist

      - name: Create a GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Netlify Deployment #${{ github.run_number }}"
          body: "Deployment for build number #${{ github.run_number }} is complete."
          draft: false
          prerelease: false

      - name: Zip Build Directory
        run: zip -r production_build.zip dist

      - name: Upload Production Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./production_build.zip
          asset_name: production_build.zip
          asset_content_type: application/zip

      - name: List Netlify Sites
        run: netlify api listSites --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
