name: CI/CD for Netlify Deployment

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x" # Use the Node.js version required by your project

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.nfp_E6YwaAM2uN7RiPYwafXuj6ZpGtg46yLT87ac }}
          NETLIFY_SITE_ID: ${{ secrets.c748c8fe-6609-439e-846b-ed45454e6889 }}
        run: npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=build

      - name: Create a GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Netlify Deployment #${{ github.run_number }}"
          body: "Deployment for build number #${{ github.run_number }} is complete."
          draft: false
          prerelease: false

      - name: Upload Production Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build
          asset_name: production_build.zip
          asset_content_type: application/zip
